[build]
  publish = "docs/.vitepress/dist"
  command = "npm run netlify-build"

[build.environment]
  NODE_VERSION = "18"
  # Explicitly disable other languages that might be auto-detected
  GO_VERSION = ""
  RUBY_VERSION = ""
  PYTHON_VERSION = ""

# Redirects and headers for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 